### ISSUE TITLE
No module named 'compressai._CXX'

### ISSUE THREAD

**Issue by zara0m** [jaehanlee-mcl/DPICT#1]
Hello,
When I tried to run eval.py, I got this error:

File "eval.py", line 34, in <module>
    import compressai
  File "/content/DPICT/compressai/__init__.py", line 15, in <module>
    from compressai import datasets, entropy_models, layers, models, ops
  File "/content/DPICT/compressai/entropy_models/__init__.py", line 15, in <module>
    from .entropy_models import EntropyBottleneck, EntropyModel, GaussianConditional
  File "/content/DPICT/compressai/entropy_models/entropy_models.py", line 13, in <module>
    from compressai._CXX import pmf_to_quantized_cdf as _pmf_to_quantized_cdf
ModuleNotFoundError: No module named 'compressai._CXX'

Could you please help me fix it?
Thank you

**Comment by jaehanlee-mcl** [comment]
This code was written in Windows 10, python 3.7 environment. If you are working in a different environment, you may need to recompile.

For example, I recommend that you try running the compressai official code. (https://github.com/InterDigitalInc/CompressAI)
Next, you could try by overwriting our code in the compressai library.

**Comment by yitianru** [comment]
Hello,
When I tried to run eval.py, I got this error:
Model: dpict-main, metric: mse, checkpoint: checkpoint/DPICT-Main/000.pth.tar
   
data01 Enc 1.8sec, 	Save Bitstreams 0.0sec, 	Dec 8.13sec (model loading: 1.25s), 	Traceback (most recent call last):
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/yitianru/DPICT/DPICT-main/eval.py", line 582, in <module>
    main()
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/yitianru/DPICT/DPICT-main/eval.py", line 533, in main
    x_hats_post2, x_hats_post3, postprocessing_t_mean = _postprocessing(info, x_hats, postprocessing_t_mean)
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/yitianru/DPICT/DPICT-main/eval.py", line 319, in _postprocessing
    net_post2.load_state_dict(torch.load(checkpoint_post2)['state_dict'], pass_update=True)
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/yitianru/DPICT/DPICT-main/compressai/models/priors.py", line 271, in load_state_dict
    super().load_state_dict(state_dict, pass_update=pass_update)
  File "/mnt/679135f3-d669-4d3d-8bea-b8c0b7074491/yitianru/DPICT/DPICT-main/compressai/models/priors.py", line 102, in load_state_dict
    super().load_state_dict(state_dict)
  File "/home/dell/Anaconda/anaconda3/envs/dpict/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DPICT_post_net:
	size mismatch for entropy_bottleneck._matrix0: copying a param with shape torch.Size([192, 3, 1]) from checkpoint, the shape in current model is torch.Size([144, 3, 1]).
	size mismatch for entropy_bottleneck._bias0: copying a param with shape torch.Size([192, 3, 1]) from checkpoint, the shape in current model is torch.Size([144, 3, 1]).
	size mismatch for entropy_bottleneck._factor0: copying a param with shape torch.Size([192, 3, 1]) from checkpoint, the shape in current model is torch.Size([144, 3, 1]).
	...

Process finished with exit code 1

Could you please help me fix it?
Thank you
